version: '3'

services:
  frontend:
    build: ./client/
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  backend:
    build: ./server/
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/backend-app
      - node_modules_b:/usr/src/backend-app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: "mongo"
    volumes: 
      - data:/data/db
    ports:
     - "27017:27017"

volumes: 
  node_modules:
  node_modules_b:
  data: